### ISSUE TITLE
Initializr broken with Gradle 5.x

### ISSUE THREAD

**Issue by eskatos** [bmuschko/gradle-initializr#2]
Selecting the 5.x nightly currently fails:
https://gradle-initializr.cleverapps.io/starter?type=basic&testFramework=&dsl=kotlin&gradleVersion=5.1-20181015235836%2B0000&archive=zip&generate-project=

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Oct 16 10:56:29 UTC 2018
There was an unexpected error (type=Internal Server Error, status=500).
org.gradle.tooling.GradleConnectionException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-5.1-20181015235836+0000-bin.zip'.
```

Might be due to the changes to `init` in Gradle 5, see https://github.com/gradle/gradle/blob/release/subprojects/docs/src/docs/release/notes.md#build-init-plugin-improvements

**Comment by bmuschko** [comment]
Looks like the daemon had died. Not sure how I could provide you with information on a potential root cause. Please let me know what you think. I restarted the service to make it operational again.

```
2018-10-16T07:48:30-06:00 Caused by: org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
2018-10-16T07:48:30-06:00 at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:179) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:218) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:142) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:93) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:60) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:58) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:41) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:122) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:179) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:53) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:193) ~[na:na]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:41) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:47) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:59) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:84) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:48:30-06:00 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
2018-10-16T07:48:30-06:00 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
2018-10-16T07:48:30-06:00 ... 1 common frames omitted
2018-10-16T07:48:30-06:00 at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) ~[gradle-tooling-api-4.10.2.jar:4.10.2]
2018-10-16T07:50:10-06:00 java.lang.NullPointerException: null
2018-10-16T07:50:10-06:00 2018-10-16 13:50:09.845 ERROR 1852 --- [o-8080-exec-198] o.s.b.w.servlet.support.ErrorPageFilter : Forwarding to error page from request [/starter] due to exception [null]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
2018-10-16T07:50:10-06:00 at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[na:na]
2018-10-16T07:50:10-06:00 at com.bmuschko.gradle.initializr.web.GradleInitializrController.starter(GradleInitializrController.java:31) ~[classes/:na]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[servlet-api.jar:na]
2018-10-16T07:50:10-06:00 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[servlet-api.jar:na]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [tomcat-coyote.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [catalina.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-coyote.jar:8.5.11]
2018-10-16T07:50:10-06:00 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-coyote.jar:8.5.11]
2018-10-16T07:50:10-06:00 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
2018-10-16T07:50:10-06:00 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.11]
2018-10-16T07:50:10-06:00 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
2018-10-16T07:50:10-06:00 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2018-10-16T07:50:10-06:00 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.11]
```

**Comment by eskatos** [comment]
It's working now, thanks!

**Comment by bmuschko** [comment]
Let's see if this happens more often. It's likely a Gradle issue or an issue with the runtime environment.
